<div class="container-fluid">
    <div>
        <h3>Лог разработки</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Главная</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Лог разработки</li>
            </ol>
        </nav>
    </div>
	<!-- Changelogs -->
     <div class="row clearfix">
       <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
           <div class="card">
               <div class="card-body">
                   <h6 class="card-title">v4.0 <small>20 Фефраля 2022г</small></h6>
                   <ul>
                       <li> [UPDATE] Изменения дизайна.</li>
					  <li> [FIXED] Исправление багов.</li>
                   </ul>
               </div>
           </div>
       </div>
    </div>
